# -*- coding: utf-8 -*-
"""finetune-generate

Automatically generated by Colab.

"""

!pip install openai tiktoken

#OpenAI API는 보안을 위해 ** 처리함.
OPENAI_KEY = 'sk-**'

# 이 폴더 안의 모든 pdf 찾아서 텍스트 추출
FOLDER_PATH = "/content/drive/MyDrive/논문연구 공유 폴더/Finetuning Data/"

BASE_MODEL_ID = "gpt-4o-2024-08-06"

SYSTEM_MESSAGE = ""

#구글 드라이브 로드
from google.colab import drive
drive.mount('/content/drive')

import glob # glob는 파일 시스템 내에서 특정 패턴에 맞는 파일을 찾는데 사용됨.
import os
import pandas as pd

def generate_conversation(xlsx_path):
    xl = pd.read_excel(xlsx_path).dropna()
    li = xl.values.tolist()
    for human, assistant in li:
        yield [
            {"role": "system", "content": SYSTEM_MESSAGE},
            {"role": "user", "content": human},
            {"role": "assistant", "content": assistant}
        ]

conversations = []
for filename in glob.iglob(FOLDER_PATH + '**/*.xlsx', recursive=True):
    file_path = os.path.join(FOLDER_PATH, filename)
    print(file_path)
    conversations += generate_conversation(file_path)

print(len(conversations))
for i in conversations[:5]:
    print(i)

import json

with open(FOLDER_PATH + '../data.jsonl', 'w', encoding='utf-8') as f:
    for conversation in conversations:
        f.write(json.dumps({"messages": conversation}, ensure_ascii=False) + '\n')

from openai import OpenAI
import datetime

timestamp = datetime.datetime.now().strftime("%Y%m%d_%H%M%S")
client = OpenAI(api_key=OPENAI_KEY)

file_id = client.files.create(
    file=open(FOLDER_PATH + '../data.jsonl', 'rb'),
    purpose="fine-tune",
).id

job_id = client.fine_tuning.jobs.create(
    training_file=file_id,
    model=BASE_MODEL_ID,
    suffix="math_chatbot_" + timestamp
).id

print(f"Fine tuning started. job_id={job_id}")

import time

while True:
    time.sleep(5)
    job = client.fine_tuning.jobs.retrieve(job_id)
    print(job)

    if job.status == "failed":
        raise Exception("Fine tuning failed")

    if job.status == "succeeded":
        print(f"Fine tuning succeeded. model={job.fine_tuned_model}")
        break